### ISSUE TITLE
Problem with the connection

### ISSUE THREAD

**Issue by aal-hotels** [hellowearemito/dataconnector-facebook#22]
Since yesterday no connection is possible. 

Error-ID: fd7c746f
"An error occurred while requesting data from the community connector. Please report the problem to the provider of this community connector if it occurs repeatedly."

Hope this can be fixed. Best Regards

**Comment by manelhj** [comment]
Same problem here, different error ID though:
"There was an error requesting data from the community connector. Please report the issue to the provider of this community connector if this issue persists.

Error ID: ddd2937b"

Attempted several times to reconnect the connector and authorize it, no success. Is this a quick fix, or will it take a long time? Just to know if I should remove this source from the projects until it's fixed.

Thank you,

**Comment by diegocgaona** [comment]
Same problem here. I think it could be something related with the API version, because in the first time I saw the error, the error message had it in the text.

The message was:
Error: Community connector error: Facebook error: (#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v3.0. If the problem persists report an issue with the connector owner.
Código do erro: 7adceda5

I authorized again and now the error is the same of you guys:

"An error occurred while requesting data from the community connector. Please report the problem to the provider of this community connector if it occurs repeatedly."

Error-ID: bbaf99db

**Comment by djozsef** [comment]
Hello @aal-hotels @manelhj @diegocgaona,

Thank you for reporting, we are looking into it right away. I'll update you here ASAP.

**Comment by djozsef** [comment]
Hello @aal-hotels @manelhj @diegocgaona,

We had to bump the FB API version to 3.1 to continue access to FB Ad Accounts. The new version of the Data Connetor is deployed. Please re-auth and try again.

**Comment by aal-hotels** [comment]
Great work - thank you very much!!!

**Comment by djozsef** [comment]
@aal-hotels thanks for confirming

**Comment by diegocgaona** [comment]
Thanks! Works fine for me too!

**Comment by manelhj** [comment]
@djozsef Amazing! Than you very much!
